#!/usr/bin/env ruby

require 'main'
require 'csv_to_xls'

Main {
  argument('input') {
    required
    cast :string
    description 'the CSV to convert'
  }

  argument('output') {
    required
    cast :string
    description 'the XLS to create'
  }

  def run
    CsvToXls.call(params['input'].value, params['output'].value)
    exit_success!
  end
}
